with(document) {
write('	<div id="ankama_header">')
write('        <div id="site_title">')
write('            <h1><a href="#">Blue</a></h1>')
write('        </div>')
write('        <div id="ankama_menu">')
write('            <ul>')
write('                <li><a href="main.html">Title</a></li>')
write('                <li><a href="among rest.html">Agency</a></li>')
write('                <li><a href="games.html">Games</a>')
write('				<ul>')
write('					<li><a href="dofus.html">Dofus</a></li>')
write('					<li><a href="dofus arena.html">KrosMaster</a></li>')
write('					<li><a href="wakfu.html">Wakfu</a></li>')
write('					<li><a href="wakfu islands.html">Islands</a></li>')
write('					<li><a href="classes.xml">Classes</a></li>')
write('				</ul>')
write('				</li>')
write('                <li><a href="series.html">Series</a></li>')
write('            </ul>	')
write('        </div>')
write('	</div>')
}